Updates maven-project-info-reports-plugin version to 2.7
Version 2.6 caused "java.lang.NoClassDefFoundError: org/sonatype/aether/*" exception on "mvn site -PreportECC" (see https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound) and caused javadoc plugin to run out of memory